#! /bin/sh
sxhkd &
polybar &
nitrogen --restore &
picom &
cmus &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
bspc monitor -d n e k o

bspc config border_width         1
bspc config window_gap          6
bspc config focus_follows_pointer true
bspc config pointer_modifier super
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Eog state=floating
bspc rule -a portproton state=floating
bspc rule -a Legacy\ Launcher* state=floating
./.dpi/ciadpi --disorder 1 --auto=torst --tlsrec 1+s

